# Generated by Django 5.0.3 on 2024-03-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('rewards', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='NPCModel',
        ),
        migrations.AddField(
            model_name='npc',
            name='quests',
            field=models.ManyToManyField(to='pathfinder.quest'),
        ),
    ]
