# Generated by Django 5.0.3 on 2024-03-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0003_alter_npc_quests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quest',
            name='rewards',
            field=models.TextField(blank=True),
        ),
    ]
