# Generated by Django 5.0.3 on 2024-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0004_alter_quest_description_alter_quest_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_level', models.IntegerField()),
                ('rewarded_level', models.IntegerField()),
                ('awarded', models.BooleanField()),
                ('consumable', models.BooleanField()),
            ],
        ),
    ]
