# Generated by Django 5.0.3 on 2024-03-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0005_loot'),
    ]

    operations = [
        migrations.AddField(
            model_name='loot',
            name='aon_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
