# Generated by Django 5.0.3 on 2024-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0006_loot_aon_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('rewarded', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
