# Generated by Django 5.0.3 on 2024-03-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0007_goldtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldtracker',
            name='level',
            field=models.IntegerField(unique=True),
        ),
    ]
