# Generated by Django 5.0.3 on 2024-03-08 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0008_alter_goldtracker_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TWN', 'Town'), ('RGN', 'Region'), ('DNG', 'Dungeon')], max_length=3)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pathfinder.location')),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('T', 'Trivial'), ('L', 'Low'), ('M', 'Moderate'), ('S', 'Severe'), ('E', 'Extreme')], max_length=1)),
                ('monsters', models.TextField()),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pathfinder.location')),
            ],
        ),
    ]
