# Generated by Django 5.0.3 on 2024-03-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0010_location_item_level_location_notes_npc_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(choices=[('TWN', 'Town'), ('RGN', 'Region'), ('DNG', 'Dungeon'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('overview', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('encounters', models.ManyToManyField(to='pathfinder.encounter')),
                ('locations', models.ManyToManyField(to='pathfinder.location')),
                ('npcs', models.ManyToManyField(to='pathfinder.npc')),
            ],
        ),
    ]
