# Generated by Django 5.0.3 on 2024-03-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0011_alter_location_name_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='encounters',
            field=models.ManyToManyField(blank=True, to='pathfinder.encounter'),
        ),
        migrations.AlterField(
            model_name='session',
            name='locations',
            field=models.ManyToManyField(blank=True, to='pathfinder.location'),
        ),
        migrations.AlterField(
            model_name='session',
            name='npcs',
            field=models.ManyToManyField(blank=True, to='pathfinder.npc'),
        ),
    ]
