# Generated by Django 5.0.3 on 2024-03-12 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0012_alter_session_encounters_alter_session_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pathfinder.location'),
        ),
    ]
