# Generated by Django 5.0.3 on 2024-03-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0013_alter_encounter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='mts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
