# Generated by Django 5.0.3 on 2024-03-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0014_encounter_mts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='monsters',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='mts',
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster1url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster2url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster3url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster4',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster4url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster5',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster5url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster6',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster6url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster7',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster7url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster8',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monster8url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
