# Generated by Django 5.0.3 on 2024-03-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0016_rename_monster1url_encounter_monster1_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='monster1',
            new_name='monster_1',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster1_URL',
            new_name='monster_1_URL',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster2',
            new_name='monster_2',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster2_URL',
            new_name='monster_2_URL',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster3',
            new_name='monster_3',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster3_URL',
            new_name='monster_3_URL',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster4',
            new_name='monster_4',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster4_URL',
            new_name='monster_4_URL',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster5',
            new_name='monster_5',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster5_URL',
            new_name='monster_5_URL',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster6',
            new_name='monster_6',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster6_URL',
            new_name='monster_6_URL',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster7',
            new_name='monster_7',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster7_URL',
            new_name='monster_7_URL',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster8',
            new_name='monster_8',
        ),
        migrations.RenameField(
            model_name='encounter',
            old_name='monster8_URL',
            new_name='monster_8_URL',
        ),
    ]
