# Generated by Django 5.0.3 on 2024-03-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder', '0017_rename_monster1_encounter_monster_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('TWN', 'Town'), ('RGN', 'Region'), ('DNG', 'Dungeon'), ('OTH', 'Other')], default='OTH', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
